---
- name: launch a vm
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: test_vm
    target_ip: 192.168.36.59
  roles:
    - provision

- name: install opstools-pm on that provisioned vm
  hosts: test_target
  vars:
    target_ip: 192.168.36.59
    vm_name: test_vm
  roles:
    - pm_target
    - log_target

