---
- name: install collectd
  package:
    name: collectd
    state: present

# collectd doesn't start in default config
# if dns lookup doesn't work
# we don't need dns here anyways
- name: switch name lookup off
  lineinfile:
    dest: /etc/collectd.conf
    regexp: '^#FQDNLookup.*?rue'
    line: 'FQDNLookup    false'
  notify: restart collectd


- name: start collectd
  service:
    name: collectd
    state: started
    enabled: yes

- name: switch SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: place collectd cvs.conf file
  copy:
    src: cvs.conf
    dest: /etc/collectd.d/
  notify: restart collectd

- name: enable cpu plugin
  blockinfile:
    dest: /etc/collectd.conf
    block: |
      <Plugin cpu>
        ReportByCpu false
        ReportByState false
        ValuesPercentage false
      </Plugin>
  notify: restart collectd

- name: reload collectd now
  meta: flush_handlers

- name: check if cvs file exists then
  wait_for:
    path: /var/tmp/collectd-values/
    state: present
    delay: 10
