---
- name: delete OpenStack VM
  os_server:
    auth:
      auth_url: "{{auth_url}}"
      username: "{{username}}"
      password: "{{password}}"
      project_name: "{{project_name}}"
    state: absent
    name: "{{vm_name}}"
    timeout: 200
